// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: cluster.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterService_GetFrontierByEdge_FullMethodName = "/controlplane.ClusterService/GetFrontierByEdge"
	ClusterService_ListFrontiers_FullMethodName     = "/controlplane.ClusterService/ListFrontiers"
	ClusterService_ListEdges_FullMethodName         = "/controlplane.ClusterService/ListEdges"
	ClusterService_GetEdgeByID_FullMethodName       = "/controlplane.ClusterService/GetEdgeByID"
	ClusterService_GetEdgesCount_FullMethodName     = "/controlplane.ClusterService/GetEdgesCount"
	ClusterService_ListServices_FullMethodName      = "/controlplane.ClusterService/ListServices"
	ClusterService_GetServiceByID_FullMethodName    = "/controlplane.ClusterService/GetServiceByID"
	ClusterService_GetServicesCount_FullMethodName  = "/controlplane.ClusterService/GetServicesCount"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	GetFrontierByEdge(ctx context.Context, in *GetFrontierByEdgeIDRequest, opts ...grpc.CallOption) (*GetFrontierByEdgeIDResponse, error)
	ListFrontiers(ctx context.Context, in *ListFrontiersRequest, opts ...grpc.CallOption) (*ListFrontiersResponse, error)
	ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...grpc.CallOption) (*ListEdgesResponse, error)
	GetEdgeByID(ctx context.Context, in *GetEdgeByIDRequest, opts ...grpc.CallOption) (*GetEdgeByIDResponse, error)
	GetEdgesCount(ctx context.Context, in *GetEdgesCountRequest, opts ...grpc.CallOption) (*GetEdgesCountResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetServiceByID(ctx context.Context, in *GetServiceByIDRequest, opts ...grpc.CallOption) (*GetServiceByIDResponse, error)
	GetServicesCount(ctx context.Context, in *GetServicesCountRequest, opts ...grpc.CallOption) (*GetServicesCountResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetFrontierByEdge(ctx context.Context, in *GetFrontierByEdgeIDRequest, opts ...grpc.CallOption) (*GetFrontierByEdgeIDResponse, error) {
	out := new(GetFrontierByEdgeIDResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetFrontierByEdge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ListFrontiers(ctx context.Context, in *ListFrontiersRequest, opts ...grpc.CallOption) (*ListFrontiersResponse, error) {
	out := new(ListFrontiersResponse)
	err := c.cc.Invoke(ctx, ClusterService_ListFrontiers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...grpc.CallOption) (*ListEdgesResponse, error) {
	out := new(ListEdgesResponse)
	err := c.cc.Invoke(ctx, ClusterService_ListEdges_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetEdgeByID(ctx context.Context, in *GetEdgeByIDRequest, opts ...grpc.CallOption) (*GetEdgeByIDResponse, error) {
	out := new(GetEdgeByIDResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetEdgeByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetEdgesCount(ctx context.Context, in *GetEdgesCountRequest, opts ...grpc.CallOption) (*GetEdgesCountResponse, error) {
	out := new(GetEdgesCountResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetEdgesCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ClusterService_ListServices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetServiceByID(ctx context.Context, in *GetServiceByIDRequest, opts ...grpc.CallOption) (*GetServiceByIDResponse, error) {
	out := new(GetServiceByIDResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetServiceByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetServicesCount(ctx context.Context, in *GetServicesCountRequest, opts ...grpc.CallOption) (*GetServicesCountResponse, error) {
	out := new(GetServicesCountResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetServicesCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility
type ClusterServiceServer interface {
	GetFrontierByEdge(context.Context, *GetFrontierByEdgeIDRequest) (*GetFrontierByEdgeIDResponse, error)
	ListFrontiers(context.Context, *ListFrontiersRequest) (*ListFrontiersResponse, error)
	ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error)
	GetEdgeByID(context.Context, *GetEdgeByIDRequest) (*GetEdgeByIDResponse, error)
	GetEdgesCount(context.Context, *GetEdgesCountRequest) (*GetEdgesCountResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetServiceByID(context.Context, *GetServiceByIDRequest) (*GetServiceByIDResponse, error)
	GetServicesCount(context.Context, *GetServicesCountRequest) (*GetServicesCountResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (UnimplementedClusterServiceServer) GetFrontierByEdge(context.Context, *GetFrontierByEdgeIDRequest) (*GetFrontierByEdgeIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrontierByEdge not implemented")
}
func (UnimplementedClusterServiceServer) ListFrontiers(context.Context, *ListFrontiersRequest) (*ListFrontiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFrontiers not implemented")
}
func (UnimplementedClusterServiceServer) ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEdges not implemented")
}
func (UnimplementedClusterServiceServer) GetEdgeByID(context.Context, *GetEdgeByIDRequest) (*GetEdgeByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdgeByID not implemented")
}
func (UnimplementedClusterServiceServer) GetEdgesCount(context.Context, *GetEdgesCountRequest) (*GetEdgesCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdgesCount not implemented")
}
func (UnimplementedClusterServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedClusterServiceServer) GetServiceByID(context.Context, *GetServiceByIDRequest) (*GetServiceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceByID not implemented")
}
func (UnimplementedClusterServiceServer) GetServicesCount(context.Context, *GetServicesCountRequest) (*GetServicesCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServicesCount not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_GetFrontierByEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrontierByEdgeIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetFrontierByEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetFrontierByEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetFrontierByEdge(ctx, req.(*GetFrontierByEdgeIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ListFrontiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFrontiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListFrontiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ListFrontiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListFrontiers(ctx, req.(*ListFrontiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ListEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ListEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListEdges(ctx, req.(*ListEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetEdgeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetEdgeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetEdgeByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetEdgeByID(ctx, req.(*GetEdgeByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetEdgesCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetEdgesCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetEdgesCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetEdgesCount(ctx, req.(*GetEdgesCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetServiceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetServiceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetServiceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetServiceByID(ctx, req.(*GetServiceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetServicesCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicesCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetServicesCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetServicesCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetServicesCount(ctx, req.(*GetServicesCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrontierByEdge",
			Handler:    _ClusterService_GetFrontierByEdge_Handler,
		},
		{
			MethodName: "ListFrontiers",
			Handler:    _ClusterService_ListFrontiers_Handler,
		},
		{
			MethodName: "ListEdges",
			Handler:    _ClusterService_ListEdges_Handler,
		},
		{
			MethodName: "GetEdgeByID",
			Handler:    _ClusterService_GetEdgeByID_Handler,
		},
		{
			MethodName: "GetEdgesCount",
			Handler:    _ClusterService_GetEdgesCount_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ClusterService_ListServices_Handler,
		},
		{
			MethodName: "GetServiceByID",
			Handler:    _ClusterService_GetServiceByID_Handler,
		},
		{
			MethodName: "GetServicesCount",
			Handler:    _ClusterService_GetServicesCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
