// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: controlplane.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFrontierByEdgeIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeId uint64 `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
}

func (x *GetFrontierByEdgeIDRequest) Reset() {
	*x = GetFrontierByEdgeIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontierByEdgeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontierByEdgeIDRequest) ProtoMessage() {}

func (x *GetFrontierByEdgeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontierByEdgeIDRequest.ProtoReflect.Descriptor instead.
func (*GetFrontierByEdgeIDRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *GetFrontierByEdgeIDRequest) GetEdgeId() uint64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

type Frontier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrontierId       string `protobuf:"bytes,1,opt,name=frontier_id,json=frontierId,proto3" json:"frontier_id,omitempty"`
	AdvertisedSbAddr string `protobuf:"bytes,2,opt,name=advertised_sb_addr,json=advertisedSbAddr,proto3" json:"advertised_sb_addr,omitempty"`
	AdvertisedEbAddr string `protobuf:"bytes,3,opt,name=advertised_eb_addr,json=advertisedEbAddr,proto3" json:"advertised_eb_addr,omitempty"`
}

func (x *Frontier) Reset() {
	*x = Frontier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frontier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frontier) ProtoMessage() {}

func (x *Frontier) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frontier.ProtoReflect.Descriptor instead.
func (*Frontier) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Frontier) GetFrontierId() string {
	if x != nil {
		return x.FrontierId
	}
	return ""
}

func (x *Frontier) GetAdvertisedSbAddr() string {
	if x != nil {
		return x.AdvertisedSbAddr
	}
	return ""
}

func (x *Frontier) GetAdvertisedEbAddr() string {
	if x != nil {
		return x.AdvertisedEbAddr
	}
	return ""
}

type GetFrontierByEdgeIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fontier *Frontier `protobuf:"bytes,1,opt,name=fontier,proto3" json:"fontier,omitempty"`
}

func (x *GetFrontierByEdgeIDResponse) Reset() {
	*x = GetFrontierByEdgeIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontierByEdgeIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontierByEdgeIDResponse) ProtoMessage() {}

func (x *GetFrontierByEdgeIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontierByEdgeIDResponse.ProtoReflect.Descriptor instead.
func (*GetFrontierByEdgeIDResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *GetFrontierByEdgeIDResponse) GetFontier() *Frontier {
	if x != nil {
		return x.Fontier
	}
	return nil
}

type GetFrontierByEdgeIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeIds []uint64 `protobuf:"varint,1,rep,packed,name=edge_ids,json=edgeIds,proto3" json:"edge_ids,omitempty"`
}

func (x *GetFrontierByEdgeIDsRequest) Reset() {
	*x = GetFrontierByEdgeIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontierByEdgeIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontierByEdgeIDsRequest) ProtoMessage() {}

func (x *GetFrontierByEdgeIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontierByEdgeIDsRequest.ProtoReflect.Descriptor instead.
func (*GetFrontierByEdgeIDsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *GetFrontierByEdgeIDsRequest) GetEdgeIds() []uint64 {
	if x != nil {
		return x.EdgeIds
	}
	return nil
}

type GetFrontiersByEdgeIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frontiers []*Frontier `protobuf:"bytes,1,rep,name=frontiers,proto3" json:"frontiers,omitempty"`
}

func (x *GetFrontiersByEdgeIDsResponse) Reset() {
	*x = GetFrontiersByEdgeIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontiersByEdgeIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontiersByEdgeIDsResponse) ProtoMessage() {}

func (x *GetFrontiersByEdgeIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontiersByEdgeIDsResponse.ProtoReflect.Descriptor instead.
func (*GetFrontiersByEdgeIDsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *GetFrontiersByEdgeIDsResponse) GetFrontiers() []*Frontier {
	if x != nil {
		return x.Frontiers
	}
	return nil
}

var File_controlplane_proto protoreflect.FileDescriptor

var file_controlplane_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x42,
	0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x08, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x69, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x64, 0x5f, 0x73, 0x62, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x64, 0x53, 0x62, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x64, 0x5f, 0x65, 0x62, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x64, 0x45, 0x62, 0x41, 0x64, 0x64,
	0x72, 0x22, 0x4f, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72,
	0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x07, 0x66, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x52, 0x07, 0x66, 0x6f, 0x6e, 0x74, 0x69,
	0x65, 0x72, 0x22, 0x38, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65,
	0x72, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x07, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x73, 0x42, 0x79, 0x45, 0x64,
	0x67, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x09, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69,
	0x65, 0x72, 0x73, 0x32, 0xee, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x69, 0x65, 0x72, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72,
	0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x72, 0x0a, 0x18, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x69, 0x65, 0x72, 0x73, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x45, 0x64, 0x67, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x69, 0x61, 0x2f, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x69, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData = file_controlplane_proto_rawDesc
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(file_controlplane_proto_rawDescData)
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controlplane_proto_goTypes = []interface{}{
	(*GetFrontierByEdgeIDRequest)(nil),    // 0: controlplane.GetFrontierByEdgeIDRequest
	(*Frontier)(nil),                      // 1: controlplane.Frontier
	(*GetFrontierByEdgeIDResponse)(nil),   // 2: controlplane.GetFrontierByEdgeIDResponse
	(*GetFrontierByEdgeIDsRequest)(nil),   // 3: controlplane.GetFrontierByEdgeIDsRequest
	(*GetFrontiersByEdgeIDsResponse)(nil), // 4: controlplane.GetFrontiersByEdgeIDsResponse
}
var file_controlplane_proto_depIdxs = []int32{
	1, // 0: controlplane.GetFrontierByEdgeIDResponse.fontier:type_name -> controlplane.Frontier
	1, // 1: controlplane.GetFrontiersByEdgeIDsResponse.frontiers:type_name -> controlplane.Frontier
	0, // 2: controlplane.ClusterService.GetFrontierByEdge:input_type -> controlplane.GetFrontierByEdgeIDRequest
	3, // 3: controlplane.ClusterService.MultiGetFrontiersByEdges:input_type -> controlplane.GetFrontierByEdgeIDsRequest
	2, // 4: controlplane.ClusterService.GetFrontierByEdge:output_type -> controlplane.GetFrontierByEdgeIDResponse
	4, // 5: controlplane.ClusterService.MultiGetFrontiersByEdges:output_type -> controlplane.GetFrontiersByEdgeIDsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controlplane_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontierByEdgeIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frontier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontierByEdgeIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontierByEdgeIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontiersByEdgeIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controlplane_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_rawDesc = nil
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
