// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.9
// source: controlplane.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationControlPlaneListEdges = "/controlplane.ControlPlane/ListEdges"

type ControlPlaneHTTPServer interface {
	ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error)
}

func RegisterControlPlaneHTTPServer(s *http.Server, srv ControlPlaneHTTPServer) {
	r := s.Route("/")
	r.GET("/v1", _ControlPlane_ListEdges0_HTTP_Handler(srv))
}

func _ControlPlane_ListEdges0_HTTP_Handler(srv ControlPlaneHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEdgesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationControlPlaneListEdges)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEdges(ctx, req.(*ListEdgesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEdgesResponse)
		return ctx.Result(200, reply)
	}
}

type ControlPlaneHTTPClient interface {
	ListEdges(ctx context.Context, req *ListEdgesRequest, opts ...http.CallOption) (rsp *ListEdgesResponse, err error)
}

type ControlPlaneHTTPClientImpl struct {
	cc *http.Client
}

func NewControlPlaneHTTPClient(client *http.Client) ControlPlaneHTTPClient {
	return &ControlPlaneHTTPClientImpl{client}
}

func (c *ControlPlaneHTTPClientImpl) ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...http.CallOption) (*ListEdgesResponse, error) {
	var out ListEdgesResponse
	pattern := "/v1"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationControlPlaneListEdges))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
